#pragma once

// Include all command headers for convenience
#include "commands/EchoCommand.hpp"
#include "commands/PingCommand.hpp"
#include "commands/SetCommand.hpp"
#include "commands/GetCommand.hpp"
#include "commands/InfoCommand.hpp"
#include "commands/ReplConfCommand.hpp"
#include "commands/PsyncCommand.hpp"
#include "commands/WaitCommand.hpp"
#include "commands/TypeCommand.hpp"
#include "commands/XaddCommand.hpp"
#include "commands/XrangeCommand.hpp"
#include "commands/XreadCommand.hpp"
#include "commands/IncrCommand.hpp"
#include "commands/MultiCommand.hpp"
#include "commands/ExecCommand.hpp"
#include "commands/DiscardCommand.hpp"
#include "commands/ConfigCommand.hpp"
#include "commands/KeysCommand.hpp"
#include "commands/RpushCommand.hpp"
#include "commands/LpushCommand.hpp"
#include "commands/LlenCommand.hpp"
#include "commands/LpopCommand.hpp"
#include "commands/LrangeCommand.hpp"
#include "commands/BlpopCommand.hpp"